name: build

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      JAVA_OPTS: "-Xmx6G"
      SBT_OPTS: "-Dsbt.ci=true -Xss100M"
    steps:
      - uses: actions/checkout@v5

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Setup sbt
        uses: sbt/setup-sbt@v1

      - name: Cache SBT
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
            ~/.ivy2/cache
            ~/.cache/coursier
            ~/.sbt/launchers
            ~/.sbt/boot
            ~/.sbt/preloaded
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt', '**/plugins.sbt', '**/build.properties') }}

      - name: Test
        run: |
          sbt \
            "headerCheckAll" \
            "scalafmtSbtCheck" \
            "scalafmtCheckAll" \
            "spotlessCheck" \
            "scalafixAll --check" \
            "test"
